name: Monthly dependency update

on:
  schedule:
    - cron: "0 0 1 * *" # 毎月1日 00:00 UTC（日本時間9:00）
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Update dependencies
        id: deps
        run: |
          set -e
          npm install -g npm-check-updates

          ncu -u
          npm install || {
            echo "npm install failed after dependency update"
            exit 1
          }

          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No dependency updates found."
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Get current year and month
        id: date
        run: echo "yearmonth=$(date +'%Y%m')" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.deps.outputs.has_changes == 'true'
        env:
          YEAR_MONTH: ${{ steps.date.outputs.yearmonth }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          BRANCH="chore/deps-${YEAR_MONTH}"

          git fetch origin master
          git checkout -B "$BRANCH" origin/master

          git add package.json package-lock.json
          git commit -m "chore: monthly dependency update (${YEAR_MONTH})"

      - name: Create Pull Request
        if: steps.deps.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/deps-${{ steps.date.outputs.yearmonth }}
          title: "chore: Monthly dependency update (${{ steps.date.outputs.yearmonth }})"
          body: |
            This PR updates all dependencies to their latest versions.
            Automatically generated by GitHub Actions.
          labels: dependencies
          base: master
