name: Test and Deploy

on:
  push:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/ci-common.yaml
    with:
      with-e2e: true

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        id: setup_node
        with:
          node-version: 22

      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.arch }}-${{ runner.os }}-node-${{ steps.setup_node.outputs.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}

      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --omit=dev

      - run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
