name: Test and Deploy

on:
  push:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/ci-common.yaml
    with:
      with-e2e: true

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        id: setup_node
        with:
          node-version: 22

      - run: npm ci --omit=dev

      - run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
